### ISSUE TITLE
Audio should be available in mp3 format.

### ISSUE THREAD

**Issue by sanskar10100** [oo7coolutsav/ytdownloader#5]
Find a webm to mp3 converter library. Surely one exists. It's python.

**Comment by sanskar10100** [comment]
Convert implicitly, user should see mp3 option only, not webm

**Comment by utgupta27** [comment]
Since, By default Youtube API dosen't provide any audio/mp3 stream .
It only provides audio/mp4a,web,acc,opus stream because Mp4A is commonly used to stream large audio tracks, such as music or podcasts. It's a common file type that has quality audio at a smaller, more manageable size.
I changed the stream to audio/mp4a. Now it downloads .mp4a files which are quite common.

**Comment by utgupta27** [comment]
resolved
